TillerConnectionURI: "127.0.0.1:44134"
StaticFeeds:
  -
    Link: https://github.com/kubernetes/kops/releases.atom
    Name: Kops
    Installed: 1.11.0
FeedMap:
  -
    Link: https://github.com/prometheus/prometheus/releases.atom
    Name: prometheus
