apiVersion: v1
data:
{{- if .Values.feedsConfig }}
  feeds.yaml: |
{{ .Values.feedsConfig | indent 4 }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    app: {{ template "k8versiontrack.fullname" $ }}
    release: {{ template "k8versiontrack.fullname" $ }}
    chart: {{ template "k8versiontrack.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  name: {{ template "k8versiontrack.fullname" $ }}-feeds
