apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8versiontrack.fullname" $ }}
  labels:
    app: {{ template "k8versiontrack.fullname" $ }}
    chart: {{ template "k8versiontrack.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: {{ template "k8versiontrack.fullname" $ }}
    release: {{ $.Release.Name }}
